[project]

site_name = "Tucker Island"
site_description = "Documentation for all of Tucker Island's Discord Features"
site_author = "mat @xyb"
#site_url = "https://www.example.com/"

repo_name = "lovebuggedd/TuckerIsland"
repo_url = "https://github.com/love-buggedd/TuckerIsland"
repo = "fontawesome/brands/github"

copyright = "Copyright &copy; 2026 @xyb"

extra_css = ["stylesheets/extra.css"]
extra_javascript = ["javascripts/font-toggle.js"]

nav = [
    "index.md",
    "vefora.md",
    "economy.md",
    {"Court" = [
        "court/index.md",
    ]}
]


[project.theme]
# variant = "classic"

font.text = "Funnel Display"
language = "en"

features = [
    "search.highlight",
    "content.tabs.link",
    # "content.code.select",
    "content.code.copy",
]

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.tables]
[project.markdown_extensions.admonition]

[project.markdown_extensions.def_list]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.extra.status]
wip = "WIP"

[project.extra]
generator = false